---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: install httpd package
    dnf:
      update_cache: yes
    when: ansible_os_family == "RedHat"
