---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: install httpd package
    dnf:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
