---

  - hosts: all
    become: true
    tasks:
    - name: Update Debian servers
      apt:
        upgrade: dist 
      when: ansible_os_family == "Debian"

    - name: Update RedHat servers
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"

  - hosts: all
    become: true
    roles:
      - base

  - hosts: debian_family
    become: true
    roles:
      - Debian_family

  - hosts: redhat_family
    become: true
    roles:
      - RedHat_family
