---

- hosts: all
  become: true
  tasks:

    - name: restart-service httpd in rocky
      service:
        name: httpd.service
        state: restarted
      when: ansible_os_family == "RedHat"

    