- name: add ssh key for simone
  ansible.posix.authorized_key:
      user: simone
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMa2ctZ+3vF40Aff7magvxWnBPHhYXBAtq2SAiCqBFTr ansible@rocky2

- name: initial config for sshd file in RedHat OS
  template:
    src: "{{ ssh_config_file }}"
    dest: /etc/ssh/sshd_config
  notify: restart_ssh